=== mrrishit909/sentinel-anomaly-lab/data/contracts/window.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "additionalProperties": false,
 "properties": {
  "affected": {
   "items": {
    "type": "string"
   },
   "type": "array"
  },
  "anomaly_end": {
   "type": "integer"
  },
  "anomaly_start": {
   "type": "integer"
  },
  "category": {
   "type": "integer"
  },
  "channel_range": {
   "additionalProperties": false,
   "properties": {
    "adbr": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "adfl": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "aimp": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "amud": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "arnd": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "asin1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "asin2": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bed1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bed2": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bfo1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bfo2": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bso1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bso2": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "bso3": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "ced1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "cfo1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    },
    "cso1": {
     "items": {
      "type": "number"
     },
     "maxItems": 2,
     "minItems": 2,
     "type": "array"
    }
   },
   "required": [
    "aimp",
    "amud",
    "arnd",
    "asin1",
    "asin2",
    "adbr",
    "adfl",
    "bed1",
    "bed2",
    "bfo1",
    "bfo2",
    "bso1",
    "bso2",
    "bso3",
    "ced1",
    "cfo1",
    "cso1"
   ],
   "type": "object"
  },
  "channels_u16": {
   "additionalProperties": false,
   "properties": {
    "adbr": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "adfl": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "aimp": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "amud": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "arnd": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "asin1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "asin2": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bed1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bed2": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bfo1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bfo2": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bso1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bso2": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "bso3": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "ced1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "cfo1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "cso1": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    }
   },
   "required": [
    "aimp",
    "amud",
    "arnd",
    "asin1",
    "asin2",
    "adbr",
    "adfl",
    "bed1",
    "bed2",
    "bfo1",
    "bfo2",
    "bso1",
    "bso2",
    "bso3",
    "ced1",
    "cfo1",
    "cso1"
   ],
   "type": "object"
  },
  "encoding": {
   "type": "string"
  },
  "id": {
   "type": "string"
  },
  "incident_id": {
   "type": "integer"
  },
  "labels_u8": {
   "pattern": "^[A-Za-z0-9+/]*={0,2}$",
   "type": "string"
  },
  "n": {
   "type": "integer"
  },
  "root_cause": {
   "enum": [
    "bed1",
    "bed2",
    "bfo1",
    "bfo2",
    "bso1",
    "bso2",
    "bso3",
    "ced1",
    "cfo1",
    "cso1"
   ]
  },
  "row0": {
   "type": "integer"
  },
  "schema_version": {
   "const": "v1"
  },
  "scores_q_u16": {
   "additionalProperties": false,
   "properties": {
    "changepoint": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "gbm": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "iforest": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "pca": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    },
    "robust_z": {
     "pattern": "^[A-Za-z0-9+/]*={0,2}$",
     "type": "string"
    }
   },
   "required": [
    "robust_z",
    "pca",
    "iforest",
    "changepoint",
    "gbm"
   ],
   "type": "object"
  },
  "split": {
   "enum": [
    "train",
    "gbm_fit",
    "val",
    "test"
   ]
  },
  "tags": {
   "additionalProperties": {
    "pattern": "^(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC)(/(OBSERVED|DERIVED|PREDICTED|SIMULATED|SYNTHETIC))*$",
    "type": "string"
   },
   "minProperties": 1,
   "type": "object"
  },
  "truncated": {
   "type": "boolean"
  }
 },
 "required": [
  "schema_version",
  "tags",
  "id",
  "incident_id",
  "split",
  "category",
  "root_cause",
  "affected",
  "row0",
  "n",
  "anomaly_start",
  "anomaly_end",
  "truncated",
  "encoding",
  "labels_u8",
  "channels_u16",
  "channel_range",
  "scores_q_u16"
 ],
 "title": "window",
 "type": "object"
}

=== mrrishit909/sentinel-anomaly-lab/site/public/data/window_140.json
{"affected":["ced1"],"anomaly_end":700,"anomaly_start":300,"category":13,"channel_range":{"adbr":[0.0,1.0],"adfl":[0.0,1.0],"aimp":[0.0,1.0],"amud":[-47.0,37.0],"arnd":[10.0,50.0],"asin1":[-1.0,1.0],"asin2":[-1.0,1.0],"bed1":[-8.488070487976074,16.77479362487793],"bed2":[-4.6753458976745605,10.149064064025879],"bfo1":[-117.55878448486328,780.3936157226562],"bfo2":[-172.09375,1306.2567138671875],"bso1":[-89.5602798461914,129.02537536621094],"bso2":[-11.261865615844727,34.513702392578125],"bso3":[-1.4568825960159302,8.804987907409668],"ced1":[-808.0387573242188,6354.1982421875],"cfo1":[-156.03713989257812,127.56649780273438],"cso1":[-203.03143310546875,296.1995544433594]},"channels_u16":{"adbr":"AAAAAAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","adfl":"/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////////////////////////////////////////////////////////////////////8=","aimp":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","amud":"DIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDDIMMgwyDGIYYhhiGGIYYhhiGGIYYhhiGGIYYhhiGGIYYhhiGGIYYhhiGGIYYhhiGGIbDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMNww3DDcMN
